// Code generated by ent, DO NOT EDIT.

package invoicesequence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldTenantID, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldEnvironmentID, v))
}

// YearMonth applies equality check predicate on the "year_month" field. It's identical to YearMonthEQ.
func YearMonth(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldYearMonth, v))
}

// LastValue applies equality check predicate on the "last_value" field. It's identical to LastValueEQ.
func LastValue(v int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldLastValue, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldContainsFold(FieldTenantID, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// YearMonthEQ applies the EQ predicate on the "year_month" field.
func YearMonthEQ(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldYearMonth, v))
}

// YearMonthNEQ applies the NEQ predicate on the "year_month" field.
func YearMonthNEQ(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNEQ(FieldYearMonth, v))
}

// YearMonthIn applies the In predicate on the "year_month" field.
func YearMonthIn(vs ...string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIn(FieldYearMonth, vs...))
}

// YearMonthNotIn applies the NotIn predicate on the "year_month" field.
func YearMonthNotIn(vs ...string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotIn(FieldYearMonth, vs...))
}

// YearMonthGT applies the GT predicate on the "year_month" field.
func YearMonthGT(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGT(FieldYearMonth, v))
}

// YearMonthGTE applies the GTE predicate on the "year_month" field.
func YearMonthGTE(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGTE(FieldYearMonth, v))
}

// YearMonthLT applies the LT predicate on the "year_month" field.
func YearMonthLT(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLT(FieldYearMonth, v))
}

// YearMonthLTE applies the LTE predicate on the "year_month" field.
func YearMonthLTE(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLTE(FieldYearMonth, v))
}

// YearMonthContains applies the Contains predicate on the "year_month" field.
func YearMonthContains(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldContains(FieldYearMonth, v))
}

// YearMonthHasPrefix applies the HasPrefix predicate on the "year_month" field.
func YearMonthHasPrefix(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldHasPrefix(FieldYearMonth, v))
}

// YearMonthHasSuffix applies the HasSuffix predicate on the "year_month" field.
func YearMonthHasSuffix(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldHasSuffix(FieldYearMonth, v))
}

// YearMonthEqualFold applies the EqualFold predicate on the "year_month" field.
func YearMonthEqualFold(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEqualFold(FieldYearMonth, v))
}

// YearMonthContainsFold applies the ContainsFold predicate on the "year_month" field.
func YearMonthContainsFold(v string) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldContainsFold(FieldYearMonth, v))
}

// LastValueEQ applies the EQ predicate on the "last_value" field.
func LastValueEQ(v int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldLastValue, v))
}

// LastValueNEQ applies the NEQ predicate on the "last_value" field.
func LastValueNEQ(v int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNEQ(FieldLastValue, v))
}

// LastValueIn applies the In predicate on the "last_value" field.
func LastValueIn(vs ...int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIn(FieldLastValue, vs...))
}

// LastValueNotIn applies the NotIn predicate on the "last_value" field.
func LastValueNotIn(vs ...int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotIn(FieldLastValue, vs...))
}

// LastValueGT applies the GT predicate on the "last_value" field.
func LastValueGT(v int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGT(FieldLastValue, v))
}

// LastValueGTE applies the GTE predicate on the "last_value" field.
func LastValueGTE(v int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGTE(FieldLastValue, v))
}

// LastValueLT applies the LT predicate on the "last_value" field.
func LastValueLT(v int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLT(FieldLastValue, v))
}

// LastValueLTE applies the LTE predicate on the "last_value" field.
func LastValueLTE(v int64) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLTE(FieldLastValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceSequence) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceSequence) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceSequence) predicate.InvoiceSequence {
	return predicate.InvoiceSequence(sql.NotPredicates(p))
}
