// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/addonassociation"
	"github.com/flexprice/flexprice/ent/predicate"
)

// AddonAssociationQuery is the builder for querying AddonAssociation entities.
type AddonAssociationQuery struct {
	config
	ctx        *QueryContext
	order      []addonassociation.OrderOption
	inters     []Interceptor
	predicates []predicate.AddonAssociation
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AddonAssociationQuery builder.
func (aaq *AddonAssociationQuery) Where(ps ...predicate.AddonAssociation) *AddonAssociationQuery {
	aaq.predicates = append(aaq.predicates, ps...)
	return aaq
}

// Limit the number of records to be returned by this query.
func (aaq *AddonAssociationQuery) Limit(limit int) *AddonAssociationQuery {
	aaq.ctx.Limit = &limit
	return aaq
}

// Offset to start from.
func (aaq *AddonAssociationQuery) Offset(offset int) *AddonAssociationQuery {
	aaq.ctx.Offset = &offset
	return aaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aaq *AddonAssociationQuery) Unique(unique bool) *AddonAssociationQuery {
	aaq.ctx.Unique = &unique
	return aaq
}

// Order specifies how the records should be ordered.
func (aaq *AddonAssociationQuery) Order(o ...addonassociation.OrderOption) *AddonAssociationQuery {
	aaq.order = append(aaq.order, o...)
	return aaq
}

// First returns the first AddonAssociation entity from the query.
// Returns a *NotFoundError when no AddonAssociation was found.
func (aaq *AddonAssociationQuery) First(ctx context.Context) (*AddonAssociation, error) {
	nodes, err := aaq.Limit(1).All(setContextOp(ctx, aaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{addonassociation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aaq *AddonAssociationQuery) FirstX(ctx context.Context) *AddonAssociation {
	node, err := aaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AddonAssociation ID from the query.
// Returns a *NotFoundError when no AddonAssociation ID was found.
func (aaq *AddonAssociationQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aaq.Limit(1).IDs(setContextOp(ctx, aaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{addonassociation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aaq *AddonAssociationQuery) FirstIDX(ctx context.Context) string {
	id, err := aaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AddonAssociation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AddonAssociation entity is found.
// Returns a *NotFoundError when no AddonAssociation entities are found.
func (aaq *AddonAssociationQuery) Only(ctx context.Context) (*AddonAssociation, error) {
	nodes, err := aaq.Limit(2).All(setContextOp(ctx, aaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{addonassociation.Label}
	default:
		return nil, &NotSingularError{addonassociation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aaq *AddonAssociationQuery) OnlyX(ctx context.Context) *AddonAssociation {
	node, err := aaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AddonAssociation ID in the query.
// Returns a *NotSingularError when more than one AddonAssociation ID is found.
// Returns a *NotFoundError when no entities are found.
func (aaq *AddonAssociationQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aaq.Limit(2).IDs(setContextOp(ctx, aaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{addonassociation.Label}
	default:
		err = &NotSingularError{addonassociation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aaq *AddonAssociationQuery) OnlyIDX(ctx context.Context) string {
	id, err := aaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AddonAssociations.
func (aaq *AddonAssociationQuery) All(ctx context.Context) ([]*AddonAssociation, error) {
	ctx = setContextOp(ctx, aaq.ctx, ent.OpQueryAll)
	if err := aaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AddonAssociation, *AddonAssociationQuery]()
	return withInterceptors[[]*AddonAssociation](ctx, aaq, qr, aaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aaq *AddonAssociationQuery) AllX(ctx context.Context) []*AddonAssociation {
	nodes, err := aaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AddonAssociation IDs.
func (aaq *AddonAssociationQuery) IDs(ctx context.Context) (ids []string, err error) {
	if aaq.ctx.Unique == nil && aaq.path != nil {
		aaq.Unique(true)
	}
	ctx = setContextOp(ctx, aaq.ctx, ent.OpQueryIDs)
	if err = aaq.Select(addonassociation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aaq *AddonAssociationQuery) IDsX(ctx context.Context) []string {
	ids, err := aaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aaq *AddonAssociationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aaq.ctx, ent.OpQueryCount)
	if err := aaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aaq, querierCount[*AddonAssociationQuery](), aaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aaq *AddonAssociationQuery) CountX(ctx context.Context) int {
	count, err := aaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aaq *AddonAssociationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aaq.ctx, ent.OpQueryExist)
	switch _, err := aaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aaq *AddonAssociationQuery) ExistX(ctx context.Context) bool {
	exist, err := aaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AddonAssociationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aaq *AddonAssociationQuery) Clone() *AddonAssociationQuery {
	if aaq == nil {
		return nil
	}
	return &AddonAssociationQuery{
		config:     aaq.config,
		ctx:        aaq.ctx.Clone(),
		order:      append([]addonassociation.OrderOption{}, aaq.order...),
		inters:     append([]Interceptor{}, aaq.inters...),
		predicates: append([]predicate.AddonAssociation{}, aaq.predicates...),
		// clone intermediate query.
		sql:  aaq.sql.Clone(),
		path: aaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AddonAssociation.Query().
//		GroupBy(addonassociation.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aaq *AddonAssociationQuery) GroupBy(field string, fields ...string) *AddonAssociationGroupBy {
	aaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AddonAssociationGroupBy{build: aaq}
	grbuild.flds = &aaq.ctx.Fields
	grbuild.label = addonassociation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.AddonAssociation.Query().
//		Select(addonassociation.FieldTenantID).
//		Scan(ctx, &v)
func (aaq *AddonAssociationQuery) Select(fields ...string) *AddonAssociationSelect {
	aaq.ctx.Fields = append(aaq.ctx.Fields, fields...)
	sbuild := &AddonAssociationSelect{AddonAssociationQuery: aaq}
	sbuild.label = addonassociation.Label
	sbuild.flds, sbuild.scan = &aaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AddonAssociationSelect configured with the given aggregations.
func (aaq *AddonAssociationQuery) Aggregate(fns ...AggregateFunc) *AddonAssociationSelect {
	return aaq.Select().Aggregate(fns...)
}

func (aaq *AddonAssociationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aaq); err != nil {
				return err
			}
		}
	}
	for _, f := range aaq.ctx.Fields {
		if !addonassociation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aaq.path != nil {
		prev, err := aaq.path(ctx)
		if err != nil {
			return err
		}
		aaq.sql = prev
	}
	return nil
}

func (aaq *AddonAssociationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AddonAssociation, error) {
	var (
		nodes = []*AddonAssociation{}
		_spec = aaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AddonAssociation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AddonAssociation{config: aaq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aaq *AddonAssociationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aaq.querySpec()
	_spec.Node.Columns = aaq.ctx.Fields
	if len(aaq.ctx.Fields) > 0 {
		_spec.Unique = aaq.ctx.Unique != nil && *aaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aaq.driver, _spec)
}

func (aaq *AddonAssociationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(addonassociation.Table, addonassociation.Columns, sqlgraph.NewFieldSpec(addonassociation.FieldID, field.TypeString))
	_spec.From = aaq.sql
	if unique := aaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aaq.path != nil {
		_spec.Unique = true
	}
	if fields := aaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, addonassociation.FieldID)
		for i := range fields {
			if fields[i] != addonassociation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aaq *AddonAssociationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aaq.driver.Dialect())
	t1 := builder.Table(addonassociation.Table)
	columns := aaq.ctx.Fields
	if len(columns) == 0 {
		columns = addonassociation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aaq.sql != nil {
		selector = aaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aaq.ctx.Unique != nil && *aaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aaq.predicates {
		p(selector)
	}
	for _, p := range aaq.order {
		p(selector)
	}
	if offset := aaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AddonAssociationGroupBy is the group-by builder for AddonAssociation entities.
type AddonAssociationGroupBy struct {
	selector
	build *AddonAssociationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aagb *AddonAssociationGroupBy) Aggregate(fns ...AggregateFunc) *AddonAssociationGroupBy {
	aagb.fns = append(aagb.fns, fns...)
	return aagb
}

// Scan applies the selector query and scans the result into the given value.
func (aagb *AddonAssociationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aagb.build.ctx, ent.OpQueryGroupBy)
	if err := aagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AddonAssociationQuery, *AddonAssociationGroupBy](ctx, aagb.build, aagb, aagb.build.inters, v)
}

func (aagb *AddonAssociationGroupBy) sqlScan(ctx context.Context, root *AddonAssociationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aagb.fns))
	for _, fn := range aagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aagb.flds)+len(aagb.fns))
		for _, f := range *aagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AddonAssociationSelect is the builder for selecting fields of AddonAssociation entities.
type AddonAssociationSelect struct {
	*AddonAssociationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aas *AddonAssociationSelect) Aggregate(fns ...AggregateFunc) *AddonAssociationSelect {
	aas.fns = append(aas.fns, fns...)
	return aas
}

// Scan applies the selector query and scans the result into the given value.
func (aas *AddonAssociationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aas.ctx, ent.OpQuerySelect)
	if err := aas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AddonAssociationQuery, *AddonAssociationSelect](ctx, aas.AddonAssociationQuery, aas, aas.inters, v)
}

func (aas *AddonAssociationSelect) sqlScan(ctx context.Context, root *AddonAssociationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aas.fns))
	for _, fn := range aas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
