// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/creditgrant"
	"github.com/flexprice/flexprice/ent/plan"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/subscription"
)

// CreditGrantQuery is the builder for querying CreditGrant entities.
type CreditGrantQuery struct {
	config
	ctx              *QueryContext
	order            []creditgrant.OrderOption
	inters           []Interceptor
	predicates       []predicate.CreditGrant
	withPlan         *PlanQuery
	withSubscription *SubscriptionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CreditGrantQuery builder.
func (cgq *CreditGrantQuery) Where(ps ...predicate.CreditGrant) *CreditGrantQuery {
	cgq.predicates = append(cgq.predicates, ps...)
	return cgq
}

// Limit the number of records to be returned by this query.
func (cgq *CreditGrantQuery) Limit(limit int) *CreditGrantQuery {
	cgq.ctx.Limit = &limit
	return cgq
}

// Offset to start from.
func (cgq *CreditGrantQuery) Offset(offset int) *CreditGrantQuery {
	cgq.ctx.Offset = &offset
	return cgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cgq *CreditGrantQuery) Unique(unique bool) *CreditGrantQuery {
	cgq.ctx.Unique = &unique
	return cgq
}

// Order specifies how the records should be ordered.
func (cgq *CreditGrantQuery) Order(o ...creditgrant.OrderOption) *CreditGrantQuery {
	cgq.order = append(cgq.order, o...)
	return cgq
}

// QueryPlan chains the current query on the "plan" edge.
func (cgq *CreditGrantQuery) QueryPlan() *PlanQuery {
	query := (&PlanClient{config: cgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(creditgrant.Table, creditgrant.FieldID, selector),
			sqlgraph.To(plan.Table, plan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, creditgrant.PlanTable, creditgrant.PlanColumn),
		)
		fromU = sqlgraph.SetNeighbors(cgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscription chains the current query on the "subscription" edge.
func (cgq *CreditGrantQuery) QuerySubscription() *SubscriptionQuery {
	query := (&SubscriptionClient{config: cgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(creditgrant.Table, creditgrant.FieldID, selector),
			sqlgraph.To(subscription.Table, subscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, creditgrant.SubscriptionTable, creditgrant.SubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(cgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CreditGrant entity from the query.
// Returns a *NotFoundError when no CreditGrant was found.
func (cgq *CreditGrantQuery) First(ctx context.Context) (*CreditGrant, error) {
	nodes, err := cgq.Limit(1).All(setContextOp(ctx, cgq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{creditgrant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cgq *CreditGrantQuery) FirstX(ctx context.Context) *CreditGrant {
	node, err := cgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CreditGrant ID from the query.
// Returns a *NotFoundError when no CreditGrant ID was found.
func (cgq *CreditGrantQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cgq.Limit(1).IDs(setContextOp(ctx, cgq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{creditgrant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cgq *CreditGrantQuery) FirstIDX(ctx context.Context) string {
	id, err := cgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CreditGrant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CreditGrant entity is found.
// Returns a *NotFoundError when no CreditGrant entities are found.
func (cgq *CreditGrantQuery) Only(ctx context.Context) (*CreditGrant, error) {
	nodes, err := cgq.Limit(2).All(setContextOp(ctx, cgq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{creditgrant.Label}
	default:
		return nil, &NotSingularError{creditgrant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cgq *CreditGrantQuery) OnlyX(ctx context.Context) *CreditGrant {
	node, err := cgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CreditGrant ID in the query.
// Returns a *NotSingularError when more than one CreditGrant ID is found.
// Returns a *NotFoundError when no entities are found.
func (cgq *CreditGrantQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cgq.Limit(2).IDs(setContextOp(ctx, cgq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{creditgrant.Label}
	default:
		err = &NotSingularError{creditgrant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cgq *CreditGrantQuery) OnlyIDX(ctx context.Context) string {
	id, err := cgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CreditGrants.
func (cgq *CreditGrantQuery) All(ctx context.Context) ([]*CreditGrant, error) {
	ctx = setContextOp(ctx, cgq.ctx, ent.OpQueryAll)
	if err := cgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CreditGrant, *CreditGrantQuery]()
	return withInterceptors[[]*CreditGrant](ctx, cgq, qr, cgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cgq *CreditGrantQuery) AllX(ctx context.Context) []*CreditGrant {
	nodes, err := cgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CreditGrant IDs.
func (cgq *CreditGrantQuery) IDs(ctx context.Context) (ids []string, err error) {
	if cgq.ctx.Unique == nil && cgq.path != nil {
		cgq.Unique(true)
	}
	ctx = setContextOp(ctx, cgq.ctx, ent.OpQueryIDs)
	if err = cgq.Select(creditgrant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cgq *CreditGrantQuery) IDsX(ctx context.Context) []string {
	ids, err := cgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cgq *CreditGrantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cgq.ctx, ent.OpQueryCount)
	if err := cgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cgq, querierCount[*CreditGrantQuery](), cgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cgq *CreditGrantQuery) CountX(ctx context.Context) int {
	count, err := cgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cgq *CreditGrantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cgq.ctx, ent.OpQueryExist)
	switch _, err := cgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cgq *CreditGrantQuery) ExistX(ctx context.Context) bool {
	exist, err := cgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CreditGrantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cgq *CreditGrantQuery) Clone() *CreditGrantQuery {
	if cgq == nil {
		return nil
	}
	return &CreditGrantQuery{
		config:           cgq.config,
		ctx:              cgq.ctx.Clone(),
		order:            append([]creditgrant.OrderOption{}, cgq.order...),
		inters:           append([]Interceptor{}, cgq.inters...),
		predicates:       append([]predicate.CreditGrant{}, cgq.predicates...),
		withPlan:         cgq.withPlan.Clone(),
		withSubscription: cgq.withSubscription.Clone(),
		// clone intermediate query.
		sql:  cgq.sql.Clone(),
		path: cgq.path,
	}
}

// WithPlan tells the query-builder to eager-load the nodes that are connected to
// the "plan" edge. The optional arguments are used to configure the query builder of the edge.
func (cgq *CreditGrantQuery) WithPlan(opts ...func(*PlanQuery)) *CreditGrantQuery {
	query := (&PlanClient{config: cgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cgq.withPlan = query
	return cgq
}

// WithSubscription tells the query-builder to eager-load the nodes that are connected to
// the "subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (cgq *CreditGrantQuery) WithSubscription(opts ...func(*SubscriptionQuery)) *CreditGrantQuery {
	query := (&SubscriptionClient{config: cgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cgq.withSubscription = query
	return cgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CreditGrant.Query().
//		GroupBy(creditgrant.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cgq *CreditGrantQuery) GroupBy(field string, fields ...string) *CreditGrantGroupBy {
	cgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CreditGrantGroupBy{build: cgq}
	grbuild.flds = &cgq.ctx.Fields
	grbuild.label = creditgrant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.CreditGrant.Query().
//		Select(creditgrant.FieldTenantID).
//		Scan(ctx, &v)
func (cgq *CreditGrantQuery) Select(fields ...string) *CreditGrantSelect {
	cgq.ctx.Fields = append(cgq.ctx.Fields, fields...)
	sbuild := &CreditGrantSelect{CreditGrantQuery: cgq}
	sbuild.label = creditgrant.Label
	sbuild.flds, sbuild.scan = &cgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CreditGrantSelect configured with the given aggregations.
func (cgq *CreditGrantQuery) Aggregate(fns ...AggregateFunc) *CreditGrantSelect {
	return cgq.Select().Aggregate(fns...)
}

func (cgq *CreditGrantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cgq); err != nil {
				return err
			}
		}
	}
	for _, f := range cgq.ctx.Fields {
		if !creditgrant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cgq.path != nil {
		prev, err := cgq.path(ctx)
		if err != nil {
			return err
		}
		cgq.sql = prev
	}
	return nil
}

func (cgq *CreditGrantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CreditGrant, error) {
	var (
		nodes       = []*CreditGrant{}
		_spec       = cgq.querySpec()
		loadedTypes = [2]bool{
			cgq.withPlan != nil,
			cgq.withSubscription != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CreditGrant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CreditGrant{config: cgq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cgq.withPlan; query != nil {
		if err := cgq.loadPlan(ctx, query, nodes, nil,
			func(n *CreditGrant, e *Plan) { n.Edges.Plan = e }); err != nil {
			return nil, err
		}
	}
	if query := cgq.withSubscription; query != nil {
		if err := cgq.loadSubscription(ctx, query, nodes, nil,
			func(n *CreditGrant, e *Subscription) { n.Edges.Subscription = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cgq *CreditGrantQuery) loadPlan(ctx context.Context, query *PlanQuery, nodes []*CreditGrant, init func(*CreditGrant), assign func(*CreditGrant, *Plan)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*CreditGrant)
	for i := range nodes {
		if nodes[i].PlanID == nil {
			continue
		}
		fk := *nodes[i].PlanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(plan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "plan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cgq *CreditGrantQuery) loadSubscription(ctx context.Context, query *SubscriptionQuery, nodes []*CreditGrant, init func(*CreditGrant), assign func(*CreditGrant, *Subscription)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*CreditGrant)
	for i := range nodes {
		if nodes[i].SubscriptionID == nil {
			continue
		}
		fk := *nodes[i].SubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cgq *CreditGrantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cgq.querySpec()
	_spec.Node.Columns = cgq.ctx.Fields
	if len(cgq.ctx.Fields) > 0 {
		_spec.Unique = cgq.ctx.Unique != nil && *cgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cgq.driver, _spec)
}

func (cgq *CreditGrantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(creditgrant.Table, creditgrant.Columns, sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString))
	_spec.From = cgq.sql
	if unique := cgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cgq.path != nil {
		_spec.Unique = true
	}
	if fields := cgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creditgrant.FieldID)
		for i := range fields {
			if fields[i] != creditgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if cgq.withPlan != nil {
			_spec.Node.AddColumnOnce(creditgrant.FieldPlanID)
		}
		if cgq.withSubscription != nil {
			_spec.Node.AddColumnOnce(creditgrant.FieldSubscriptionID)
		}
	}
	if ps := cgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cgq *CreditGrantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cgq.driver.Dialect())
	t1 := builder.Table(creditgrant.Table)
	columns := cgq.ctx.Fields
	if len(columns) == 0 {
		columns = creditgrant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cgq.sql != nil {
		selector = cgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cgq.ctx.Unique != nil && *cgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cgq.predicates {
		p(selector)
	}
	for _, p := range cgq.order {
		p(selector)
	}
	if offset := cgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CreditGrantGroupBy is the group-by builder for CreditGrant entities.
type CreditGrantGroupBy struct {
	selector
	build *CreditGrantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cggb *CreditGrantGroupBy) Aggregate(fns ...AggregateFunc) *CreditGrantGroupBy {
	cggb.fns = append(cggb.fns, fns...)
	return cggb
}

// Scan applies the selector query and scans the result into the given value.
func (cggb *CreditGrantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cggb.build.ctx, ent.OpQueryGroupBy)
	if err := cggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreditGrantQuery, *CreditGrantGroupBy](ctx, cggb.build, cggb, cggb.build.inters, v)
}

func (cggb *CreditGrantGroupBy) sqlScan(ctx context.Context, root *CreditGrantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cggb.fns))
	for _, fn := range cggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cggb.flds)+len(cggb.fns))
		for _, f := range *cggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CreditGrantSelect is the builder for selecting fields of CreditGrant entities.
type CreditGrantSelect struct {
	*CreditGrantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cgs *CreditGrantSelect) Aggregate(fns ...AggregateFunc) *CreditGrantSelect {
	cgs.fns = append(cgs.fns, fns...)
	return cgs
}

// Scan applies the selector query and scans the result into the given value.
func (cgs *CreditGrantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgs.ctx, ent.OpQuerySelect)
	if err := cgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreditGrantQuery, *CreditGrantSelect](ctx, cgs.CreditGrantQuery, cgs, cgs.inters, v)
}

func (cgs *CreditGrantSelect) sqlScan(ctx context.Context, root *CreditGrantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cgs.fns))
	for _, fn := range cgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
