// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/creditgrantapplication"
	"github.com/flexprice/flexprice/ent/predicate"
)

// CreditGrantApplicationQuery is the builder for querying CreditGrantApplication entities.
type CreditGrantApplicationQuery struct {
	config
	ctx        *QueryContext
	order      []creditgrantapplication.OrderOption
	inters     []Interceptor
	predicates []predicate.CreditGrantApplication
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CreditGrantApplicationQuery builder.
func (cgaq *CreditGrantApplicationQuery) Where(ps ...predicate.CreditGrantApplication) *CreditGrantApplicationQuery {
	cgaq.predicates = append(cgaq.predicates, ps...)
	return cgaq
}

// Limit the number of records to be returned by this query.
func (cgaq *CreditGrantApplicationQuery) Limit(limit int) *CreditGrantApplicationQuery {
	cgaq.ctx.Limit = &limit
	return cgaq
}

// Offset to start from.
func (cgaq *CreditGrantApplicationQuery) Offset(offset int) *CreditGrantApplicationQuery {
	cgaq.ctx.Offset = &offset
	return cgaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cgaq *CreditGrantApplicationQuery) Unique(unique bool) *CreditGrantApplicationQuery {
	cgaq.ctx.Unique = &unique
	return cgaq
}

// Order specifies how the records should be ordered.
func (cgaq *CreditGrantApplicationQuery) Order(o ...creditgrantapplication.OrderOption) *CreditGrantApplicationQuery {
	cgaq.order = append(cgaq.order, o...)
	return cgaq
}

// First returns the first CreditGrantApplication entity from the query.
// Returns a *NotFoundError when no CreditGrantApplication was found.
func (cgaq *CreditGrantApplicationQuery) First(ctx context.Context) (*CreditGrantApplication, error) {
	nodes, err := cgaq.Limit(1).All(setContextOp(ctx, cgaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{creditgrantapplication.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) FirstX(ctx context.Context) *CreditGrantApplication {
	node, err := cgaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CreditGrantApplication ID from the query.
// Returns a *NotFoundError when no CreditGrantApplication ID was found.
func (cgaq *CreditGrantApplicationQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cgaq.Limit(1).IDs(setContextOp(ctx, cgaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{creditgrantapplication.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) FirstIDX(ctx context.Context) string {
	id, err := cgaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CreditGrantApplication entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CreditGrantApplication entity is found.
// Returns a *NotFoundError when no CreditGrantApplication entities are found.
func (cgaq *CreditGrantApplicationQuery) Only(ctx context.Context) (*CreditGrantApplication, error) {
	nodes, err := cgaq.Limit(2).All(setContextOp(ctx, cgaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{creditgrantapplication.Label}
	default:
		return nil, &NotSingularError{creditgrantapplication.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) OnlyX(ctx context.Context) *CreditGrantApplication {
	node, err := cgaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CreditGrantApplication ID in the query.
// Returns a *NotSingularError when more than one CreditGrantApplication ID is found.
// Returns a *NotFoundError when no entities are found.
func (cgaq *CreditGrantApplicationQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cgaq.Limit(2).IDs(setContextOp(ctx, cgaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{creditgrantapplication.Label}
	default:
		err = &NotSingularError{creditgrantapplication.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) OnlyIDX(ctx context.Context) string {
	id, err := cgaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CreditGrantApplications.
func (cgaq *CreditGrantApplicationQuery) All(ctx context.Context) ([]*CreditGrantApplication, error) {
	ctx = setContextOp(ctx, cgaq.ctx, ent.OpQueryAll)
	if err := cgaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CreditGrantApplication, *CreditGrantApplicationQuery]()
	return withInterceptors[[]*CreditGrantApplication](ctx, cgaq, qr, cgaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) AllX(ctx context.Context) []*CreditGrantApplication {
	nodes, err := cgaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CreditGrantApplication IDs.
func (cgaq *CreditGrantApplicationQuery) IDs(ctx context.Context) (ids []string, err error) {
	if cgaq.ctx.Unique == nil && cgaq.path != nil {
		cgaq.Unique(true)
	}
	ctx = setContextOp(ctx, cgaq.ctx, ent.OpQueryIDs)
	if err = cgaq.Select(creditgrantapplication.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) IDsX(ctx context.Context) []string {
	ids, err := cgaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cgaq *CreditGrantApplicationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cgaq.ctx, ent.OpQueryCount)
	if err := cgaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cgaq, querierCount[*CreditGrantApplicationQuery](), cgaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) CountX(ctx context.Context) int {
	count, err := cgaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cgaq *CreditGrantApplicationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cgaq.ctx, ent.OpQueryExist)
	switch _, err := cgaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cgaq *CreditGrantApplicationQuery) ExistX(ctx context.Context) bool {
	exist, err := cgaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CreditGrantApplicationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cgaq *CreditGrantApplicationQuery) Clone() *CreditGrantApplicationQuery {
	if cgaq == nil {
		return nil
	}
	return &CreditGrantApplicationQuery{
		config:     cgaq.config,
		ctx:        cgaq.ctx.Clone(),
		order:      append([]creditgrantapplication.OrderOption{}, cgaq.order...),
		inters:     append([]Interceptor{}, cgaq.inters...),
		predicates: append([]predicate.CreditGrantApplication{}, cgaq.predicates...),
		// clone intermediate query.
		sql:  cgaq.sql.Clone(),
		path: cgaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CreditGrantApplication.Query().
//		GroupBy(creditgrantapplication.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cgaq *CreditGrantApplicationQuery) GroupBy(field string, fields ...string) *CreditGrantApplicationGroupBy {
	cgaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CreditGrantApplicationGroupBy{build: cgaq}
	grbuild.flds = &cgaq.ctx.Fields
	grbuild.label = creditgrantapplication.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.CreditGrantApplication.Query().
//		Select(creditgrantapplication.FieldTenantID).
//		Scan(ctx, &v)
func (cgaq *CreditGrantApplicationQuery) Select(fields ...string) *CreditGrantApplicationSelect {
	cgaq.ctx.Fields = append(cgaq.ctx.Fields, fields...)
	sbuild := &CreditGrantApplicationSelect{CreditGrantApplicationQuery: cgaq}
	sbuild.label = creditgrantapplication.Label
	sbuild.flds, sbuild.scan = &cgaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CreditGrantApplicationSelect configured with the given aggregations.
func (cgaq *CreditGrantApplicationQuery) Aggregate(fns ...AggregateFunc) *CreditGrantApplicationSelect {
	return cgaq.Select().Aggregate(fns...)
}

func (cgaq *CreditGrantApplicationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cgaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cgaq); err != nil {
				return err
			}
		}
	}
	for _, f := range cgaq.ctx.Fields {
		if !creditgrantapplication.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cgaq.path != nil {
		prev, err := cgaq.path(ctx)
		if err != nil {
			return err
		}
		cgaq.sql = prev
	}
	return nil
}

func (cgaq *CreditGrantApplicationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CreditGrantApplication, error) {
	var (
		nodes = []*CreditGrantApplication{}
		_spec = cgaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CreditGrantApplication).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CreditGrantApplication{config: cgaq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cgaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cgaq *CreditGrantApplicationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cgaq.querySpec()
	_spec.Node.Columns = cgaq.ctx.Fields
	if len(cgaq.ctx.Fields) > 0 {
		_spec.Unique = cgaq.ctx.Unique != nil && *cgaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cgaq.driver, _spec)
}

func (cgaq *CreditGrantApplicationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(creditgrantapplication.Table, creditgrantapplication.Columns, sqlgraph.NewFieldSpec(creditgrantapplication.FieldID, field.TypeString))
	_spec.From = cgaq.sql
	if unique := cgaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cgaq.path != nil {
		_spec.Unique = true
	}
	if fields := cgaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creditgrantapplication.FieldID)
		for i := range fields {
			if fields[i] != creditgrantapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cgaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cgaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cgaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cgaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cgaq *CreditGrantApplicationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cgaq.driver.Dialect())
	t1 := builder.Table(creditgrantapplication.Table)
	columns := cgaq.ctx.Fields
	if len(columns) == 0 {
		columns = creditgrantapplication.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cgaq.sql != nil {
		selector = cgaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cgaq.ctx.Unique != nil && *cgaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cgaq.predicates {
		p(selector)
	}
	for _, p := range cgaq.order {
		p(selector)
	}
	if offset := cgaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cgaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CreditGrantApplicationGroupBy is the group-by builder for CreditGrantApplication entities.
type CreditGrantApplicationGroupBy struct {
	selector
	build *CreditGrantApplicationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgagb *CreditGrantApplicationGroupBy) Aggregate(fns ...AggregateFunc) *CreditGrantApplicationGroupBy {
	cgagb.fns = append(cgagb.fns, fns...)
	return cgagb
}

// Scan applies the selector query and scans the result into the given value.
func (cgagb *CreditGrantApplicationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgagb.build.ctx, ent.OpQueryGroupBy)
	if err := cgagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreditGrantApplicationQuery, *CreditGrantApplicationGroupBy](ctx, cgagb.build, cgagb, cgagb.build.inters, v)
}

func (cgagb *CreditGrantApplicationGroupBy) sqlScan(ctx context.Context, root *CreditGrantApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgagb.fns))
	for _, fn := range cgagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgagb.flds)+len(cgagb.fns))
		for _, f := range *cgagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CreditGrantApplicationSelect is the builder for selecting fields of CreditGrantApplication entities.
type CreditGrantApplicationSelect struct {
	*CreditGrantApplicationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cgas *CreditGrantApplicationSelect) Aggregate(fns ...AggregateFunc) *CreditGrantApplicationSelect {
	cgas.fns = append(cgas.fns, fns...)
	return cgas
}

// Scan applies the selector query and scans the result into the given value.
func (cgas *CreditGrantApplicationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgas.ctx, ent.OpQuerySelect)
	if err := cgas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CreditGrantApplicationQuery, *CreditGrantApplicationSelect](ctx, cgas.CreditGrantApplicationQuery, cgas, cgas.inters, v)
}

func (cgas *CreditGrantApplicationSelect) sqlScan(ctx context.Context, root *CreditGrantApplicationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cgas.fns))
	for _, fn := range cgas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cgas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
