// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/subscriptionpause"
)

// SubscriptionPauseDelete is the builder for deleting a SubscriptionPause entity.
type SubscriptionPauseDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionPauseMutation
}

// Where appends a list predicates to the SubscriptionPauseDelete builder.
func (spd *SubscriptionPauseDelete) Where(ps ...predicate.SubscriptionPause) *SubscriptionPauseDelete {
	spd.mutation.Where(ps...)
	return spd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (spd *SubscriptionPauseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, spd.sqlExec, spd.mutation, spd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (spd *SubscriptionPauseDelete) ExecX(ctx context.Context) int {
	n, err := spd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (spd *SubscriptionPauseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionpause.Table, sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString))
	if ps := spd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, spd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	spd.mutation.done = true
	return affected, err
}

// SubscriptionPauseDeleteOne is the builder for deleting a single SubscriptionPause entity.
type SubscriptionPauseDeleteOne struct {
	spd *SubscriptionPauseDelete
}

// Where appends a list predicates to the SubscriptionPauseDelete builder.
func (spdo *SubscriptionPauseDeleteOne) Where(ps ...predicate.SubscriptionPause) *SubscriptionPauseDeleteOne {
	spdo.spd.mutation.Where(ps...)
	return spdo
}

// Exec executes the deletion query.
func (spdo *SubscriptionPauseDeleteOne) Exec(ctx context.Context) error {
	n, err := spdo.spd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionpause.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (spdo *SubscriptionPauseDeleteOne) ExecX(ctx context.Context) {
	if err := spdo.Exec(ctx); err != nil {
		panic(err)
	}
}
